server:
  port: 8081

spring:
  application:
    name: SOFARpc-Provider

sofa:
  boot:
    rpc:
      enable-auto-publish: false
      registry-address: zookeeper://127.0.0.1:2181
      #address: nacos://127.0.0.1:8848
