server:
  port: 8082

spring:
  application:
    name: SOFARpc-Consumer

sofa:
  boot:
    rpc:
      enable-auto-publish: true
      registry-address: zookeeper://127.0.0.1:2181
      #address: nacos://127.0.0.1:8848